import pandas as pd
import plotly.express as px
a=pd.read_csv("py dt.txt")
print("Happiness Index:")
print(a.to_string())
print("Highest GDP ranking:")
b=a["GDP ranking"].min()
c=a["GDP ranking"].max()
print("The country is USA and the rank is:",b)
print("lowest GDP ranking:")
print("The country is Venezuela and the rank is:",c)
print("comparison of Free Indices Score:")
x=a["Freedom Indices Score"].max()
y=a["Freedom Indices Score"].min()
print("The maximum FIS is Norway:",x)
print("The minimum FIS is Laos:",y)
print("basic info.:")
print(a.describe())
print("The list of GDP:")
gdp=a["GDP ranking"].tolist()
print(gdp)
print("The list of Countries:")
cnt=a["Countries"].tolist()
print(cnt)
gr=px.bar(a,x="Countries",y="Freedom Indices Score")
gr.show()
sr=px.scatter(a,x="GDP ranking",y="Freedom Indices Score",labels={"GDP ranking":"GDP ranking","Freedom Indices Score":"Freedom Indices Score"})
sr.show()